### PR TITLE
[DO-NOT-MERGE] Update guestbook manifests from k/examples repo

### PR DESCRIPTION
**Pull request by ahmetb**
- Removed existing manifests as they now live in k/examples repo
- Imported manifests from k/examples repo, edited irrelevant parts (such as
  type:NodePort comments, or GET_HOSTS_FROM=env) for GKE.
- Removed manifest comments already described in the tutorial.

Once merged, I will update guestbook tutorial to update these files instead
of k/examples directly.

cc: @jeffmendoza

### CODE REVIEW

**Comment by jeffmendoza** [comment]
Don't merge this just yet. I believe the interactive in-console tutorial uses this code

**Comment by jeffmendoza** [comment]
yes, second tutorial here: https://cloud.google.com/container-engine/docs/tutorials "Interactive tutorial on building a Guestbook app"

**Comment by ahmetb** [comment]
Thanks for the heads-up, I will pin those to an older version if possible then update them as well.

**Comment by jeffmendoza** [comment]
It would be good to have a minimal readme to point to https://cloud.google.com/container-engine/docs/tutorials/guestbook

**Pull request closed without merging**
