### PR TITLE
Migrate gke-observability-tutorials to this repository

### PR DESCRIPTION
**Pull request by dashpole**
Supersedes https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/526

cc @bourgeoisor

This copies the contents of https://github.com/GoogleCloudPlatform/gke-observability-tutorials/tree/master/gke-opencensus-stackdriver/go/http to the distributed-tracing directory in this repository.  This is part of updating this documentation page: https://cloud.google.com/architecture/using-distributed-tracing-to-observe-microservice-latency-with-opencensus-and-stackdriver-trace

Additionally, it makes the following changes:

* Update Go 1.12 -> Go 1.19
* Add go.mod and go.sum files
* Update to multi-stage docker build, and use a distroless base image (copied from [hello-app/Dockerfile](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/hello-app/Dockerfile)
* Unify the frontend and backend apps into a single binary, since they are essentially the same.
* Migrate the application to OpenTelemetry
* Add a README

### CODE REVIEW

**Comment by dashpole** [comment]
cc @punya

**Comment by dashpole** [comment]
Updated to add cloudtrace prefix to snippets

**Comment by dashpole** [comment]
This PR now also migrates the demo from OpenCensus to OpenTelemetry

**Comment by bourgeoisor** [comment]
Should we close https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/526 ?

**Comment by bourgeoisor** [comment]
@dashpole ping me when the PR is stable and ready for review!

**Review by bourgeoisor — CHANGES_REQUESTED** [review]
Could you:
- Move. this sample to `<repo-root>/monitoring/distributed-tracing` (I'm in the process of moving samples to topic-based top-level directories
- Read through the contributing guide and make sure all steps are followed. In particular, we should have dry-testing of the Docker image -- that it builds, at the very least. (https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/.github/CONTRIBUTING.md)

**Comment by dashpole** [comment]
Done

**Review by bourgeoisor — APPROVED** [review]

**Pull request merged**
