### PR TITLE
Add Ray on GKE llm examples

### PR DESCRIPTION
**Pull request by kenthua**
This PR refactors ray service / llm on GKE examples from the ai-on-gke repo.

This includes sample terraform to deploy gke and the kuberay operator
This includes the ray service and ray llm respective examples for serving llama2 and falcon models.

### CODE REVIEW

**Comment by bourgeoisor** [comment]
Since these are new files to the repo, the copyright header should reflect the current year (2024), that's what the check is complaining about :)

**Comment by bourgeoisor** [comment]
Could you add a `.github/workflows/ai-ml-gke-ray-ci.yml` file that does `terraform init` and `terraform validate` at minimum?

You can find some inspiration with the existing workflows, e.g. https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/.github/workflows/cost-optimization-gke-vpa-recommendations-ci.yml#L22-L26

**Comment by kenthua** [comment]
Thanks @bourgeoisor, updated copyright and added the gha workflow

**Comment by kenthua** [comment]
thanks, we can merge this now when you get a chance.

**Pull request merged**
