### PR TITLE
feat: samples for upcoming Istio tutorial

### PR DESCRIPTION
**Pull request by TheRealSpaceShip**
This PR contains Kubernetes manifest files for the Istio tutorial:

- CR to install Kiali server with Kiali operator
- Istio PeerAuthentication to configure STRICT mode for mTLS per namespace
- Google Managed Prometheus CR PodMonitoring to collect Istio and Envoy proxy sidecar containers metrics.

A link to the tutorial will be provided as soon as it will be published.

### CODE REVIEW

**Review by bourgeoisor — APPROVED** [review]

**Comment by bourgeoisor** [comment]
Question: Is this tutorial specifically for Autopilot?

Asking because of the directory. If it's not an Autopilot-specific tutorial, maybe we could put it in e.g. `service-mesh/istio-tutorial/`?

**Comment by TheRealSpaceShip** [comment]
> Question: Is this tutorial specifically for Autopilot?
> 
> Asking because of the directory. If it's not an Autopilot-specific tutorial, maybe we could put it in e.g. `service-mesh/istio-tutorial/`?

I wrote a tutorial for Autopilot and didn't test it against Standard GKE. But instructions in the tutorial and these manifest files are not Autopilot specific (except the requirement to enable NET_ADMIN Linux capability and install Google-managed Prometheus) So I think I could move files to `service-mesh/istio-tutorial`

**Review by NimJay — APPROVED** [review]
I'm wondering if [the Bank of Anthos /extras folder](https://github.com/GoogleCloudPlatform/bank-of-anthos/tree/main/extras) is a better place for these samples.
But approving because it was approved by Olivier (Bank of Anthos tech lead).

This looks ready to merge.
@TheRealSpaceShip are we waiting on anything else? (May I go ahead and merge this?)

Heads-up: if you're including/embedding these samples in your tutorial, you'll need to use "region tags" similar to what we see [here](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/hello-app/main.go#L18) (region tags), [here](https://cloud.google.com/kubernetes-engine/docs/deploy-app-cluster#code_review) (embedding in tutorial) and [here](https://source.corp.google.com/piper///depot/google3/googledata/devsite/site-cloud/en/kubernetes-engine/docs/deploy-app-cluster.md;l=265) (use of region tags in tutorial). Ping me if you need assistance with this.

**Comment by melissakendall** [comment]
> I'm wondering if [the Bank of Anthos /extras folder](https://github.com/GoogleCloudPlatform/bank-of-anthos/tree/main/extras) is a better place for these samples. But approving because it was approved by Olivier (Bank of Anthos tech lead).
> 
> This looks ready to merge. @TheRealSpaceShip are we waiting on anything else? (May I go ahead and merge this?)
> 
> Heads-up: if you're including/embedding these samples in your tutorial, you'll need to use "region tags" similar to what we see [here](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/hello-app/main.go#L18) (region tags), [here](https://cloud.google.com/kubernetes-engine/docs/deploy-app-cluster#code_review) (embedding in tutorial) and [here](https://source.corp.google.com/piper///depot/google3/googledata/devsite/site-cloud/en/kubernetes-engine/docs/deploy-app-cluster.md;l=265) (tutorial code referencing region tag to create embedding). Ping me if you need assistance with this.

I'm fine with keeping the samples here or on BoA - but please do add the region tags :)

**Comment by bourgeoisor** [comment]
The samples are fine here, but +1 to adding region tags.

**Review by bourgeoisor — APPROVED** [review]
LGTM.

Let me know when I can merge.

Please also create a follow-up PR once the tutorial is published to add the URL of the tutorial in the README.

**Comment by minherz** [comment]
@TheRealSpaceShip please rebase and merge

**Comment by bourgeoisor** [comment]
@TheRealSpaceShip this is still ready to be merged whenever it's ready to go, just let me know

**Comment by TheRealSpaceShip** [comment]
@bourgeoisor this PR is done and ready to be merged.

**Pull request merged**
