### PR TITLE
Migrate gke-scheduled-autoscaler sample

### PR DESCRIPTION
**Pull request by rbarberop**
Moved from github.com/GoogleCloudPlatform/gke-scheduled-autoscaler
Addresses https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/issues/392

### CODE REVIEW

**Comment by bourgeoisor** [comment]
Hi @rbarberop! Could you make sure that snippet names follow this hierarchy: `$PRODUCT_$SAMPLE_$TAG`, for example in your case something along those lines: `gke_scheduled_autoscaler_hpa`.

What is the end-goal of the github.com/GoogleCloudPlatform/gke-scheduled-autoscaler repo? Is it going to be archived in favour of this / is the tutorial going to point here instead?

**Comment by rbarberop** [comment]
Thanks for pointing that out @bourgeoisor 

The original repo will have just a README with the new address and the tutorial will point at this one in the end too.

**Comment by bourgeoisor** [comment]
Could you add the following in a new file called `.github/workflows/gke-scheduled-autoscaler-ci.yml`:

```yaml
name: gke-scheduled-autoscaler-ci
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/gke-scheduled-autoscaler-ci.yml'
      - 'gke-scheduled-autoscaler/**'
  pull_request:
    paths:
      - '.github/workflows/gke-scheduled-autoscaler-ci.yml'
      - 'gke-scheduled-autoscaler/**'
jobs:
  job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: build gke-scheduled-autoscaler container
        run: |
          cd gke-scheduled-autoscaler
          docker build --tag gke-scheduled-autoscaler .
```

**Review by bourgeoisor — APPROVED** [review]
LGTM!

**Pull request merged**
