### PR TITLE
Update Deployment examples to v1 API

### PR DESCRIPTION
**Pull request by mistyhacks**
Deployment graduated to v1 in Kubernetes 1.9.

### CODE REVIEW

**Comment by ahmetb** [comment]
Thanks.

**Comment by ahmetb** [comment]
@mistyhacks I just realized `extensions/v1 Deployment` was an invalid change. If you made the same changes in other places, please revisit them.  I'll be pushing a commit to this repo to fix it.

**Comment by pmallory** [comment]
Misty is on leave. I'll review the docs that were changed at the same time as this to see if they have this issue too.

**Comment by ahmetb** [comment]
OK, it would be great if you can republish https://cloud.google.com/kubernetes-engine/docs/tutorials/persistent-disk as well. We get a bug from that nearly every day.

**Pull request merged**
