### PR TITLE
VIT training example using GKE GCS and Filestore CSI driver

### PR DESCRIPTION
**Pull request by saikat-royc**
This PR contains artifacts of an e2e training example on GKE using GCS and Filestore CSI driver.

### CODE REVIEW

**Comment by bourgeoisor** [comment]
@saikat-royc hi! Just clarifying / checking: is this sample going to be used for a doc or tutorial that is going to be hosted here: `https://cloud.google.com/kubernetes-engine/docs/`? Or somewhere else?

**Comment by akshayram-wolverine** [comment]
This sample will be referred to in a blog post @bourgeoisor

**Comment by saikat-royc** [comment]
> @saikat-royc hi! Just clarifying / checking: is this sample going to be used for a doc or tutorial that is going to be hosted here: `https://cloud.google.com/kubernetes-engine/docs/`? Or somewhere else?

As discussed offline, I haved moved the content to demos sub-directory. PTAL @bourgeoisor

**Review by bourgeoisor — APPROVED** [review]
LGTM, let me know when it should be merged

**Pull request merged**
