### PR TITLE
Create Whereami Helm chart

### PR DESCRIPTION
**Pull request by mathieu-benoit**
Bumping to 1.2.14 to avoid overriding the current 1.2.13 version as soon as this PR is merged in `main`.

Create and expose the public Whereami Helm chart. Adding another option to deploy Whereami if you want to use Helm.

To install Whereami via its Helm chart it's as easy as running:
```
helm install whereami oci://us-docker.pkg.dev/google-samples/charts/whereami \
    --version 1.2.13
```
Via Config Sync, you can configure your `R*Syncs` like this too:
```
apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync-whereami-helm
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  sourceType: helm
  helm:
    repo: oci://us-docker.pkg.dev/google-samples/charts
    chart: whereami
    version: 1.2.13
    releaseName: whereami
    auth: none
```

- [X] Create Helm chart
- [x] Test consistency between Helm chart and Kustomize overlays's outputs
- [x] Tests in GKE cluster for both Kustomize overlays and Helm chart
- [x] Document in `README.md`
- [x] Publish the Helm chart in `google-samples`'s registry --> 1.2.13 only for now, pushed manually
- [x] Automate the push of the Helm chart in registry

In order to have consistency between Helm chart and Kustomize overlays's outputs, I simplified a bit some namings in the plain Kubernetes manifests:
- `ConfigMap` is not anymore suffixed by `-configmap`
- `ServiceAccount` is not anymore suffixed by `-ksa`
- Add `app` label for all the resources, that's what the Kustomize overlays are doing anyway, so added them in the bases `k8s` and `k8s-grpc` too.

I have done multiple tests in order to make sure there is no issues/regressions, let me know if you see anything I may have missed.

Here are some commands/use cases I have tested locally in order to check that there is no differences between both Helm chart and Kustomize overlays's outputs:
<details>
  <summary>Details to reproduce these tests, click me</summary>

For `k8s`:
```  
cd ~/kubernetes-engine-samples/whereami/k8s
#Generate Kustomize overlay's output:
kustomize edit set namespace default
kustomize build . > kustomize-output.yaml
#Generate Helm chart's output:
helm template whereami oci://us-docker.pkg.dev/google-samples/charts/whereami --version 1.2.13 > helm-template.yaml
rm kustomization.yaml
kustomize create --resources helm-template.yaml
kustomize build . > helm-output.yaml
# Verify that there is no diff between the 2 outputs:
diff kustomize-output.yaml helm-output.yaml
```

For `k8s-backend-overlay-example`:
```
cd ~/kubernetes-engine-samples/whereami/k8s-backend-overlay-example
#Generate Kustomize overlay's output:
kustomize edit set namespace default
kustomize build . > kustomize-output.yaml
#Generate Helm chart's output:
helm template whereami oci://us-docker.pkg.dev/google-samples/charts/whereami --version 1.2.13 --set suffix=-backend,config.metadata=backend,service.type=ClusterIP > helm-template.yaml
rm kustomization.yaml
kustomize create --resources helm-template.yaml
kustomize build . > helm-output.yaml
# Verify that there is no diff between the 2 outputs:
diff kustomize-output.yaml helm-output.yaml
```

For `k8s-echo-headers-overlay-example`:
```
cd ~/kubernetes-engine-samples/whereami/k8s-echo-headers-overlay-example
#Generate Kustomize overlay's output:
kustomize edit set namespace default
kustomize build . > kustomize-output.yaml
#Generate Helm chart's output:
helm template whereami oci://us-docker.pkg.dev/google-samples/charts/whereami --version 1.2.13 --set suffix=-echo-headers,config.metadata=echo_headers_enabled,config.echoHeaders.enabled=true > helm-template.yaml
rm kustomization.yaml
kustomize create --resources helm-template.yaml
kustomize build . > helm-output.yaml
# Verify that there is no diff between the 2 outputs:
diff kustomize-output.yaml helm-output.yaml
```

For `k8s-frontend-overlay-clusterip-example`:
```
cd ~/kubernetes-engine-samples/whereami/k8s-frontend-overlay-clusterip-example
#Generate Kustomize overlay's output:
kustomize edit set namespace default
kustomize build . > kustomize-output.yaml
#Generate Helm chart's output:
helm template whereami oci://us-docker.pkg.dev/google-samples/charts/whereami --version 1.2.13 --set suffix=-frontend,config.metadata=frontend,config.backend.enabled=true,service.type=ClusterIP > helm-template.yaml
rm kustomization.yaml
kustomize create --resources helm-template.yaml
kustomize build . > helm-output.yaml
# Verify that there is no diff between the 2 outputs:
diff kustomize-output.yaml helm-output.yaml
```

For `k8s-frontend-overlay-example`:
```
cd ~/kubernetes-engine-samples/whereami/k8s-frontend-overlay-example
#Generate Kustomize overlay's output:
kustomize edit set namespace default
kustomize build . > kustomize-output.yaml
#Generate Helm chart's output:
helm template whereami oci://us-docker.pkg.dev/google-samples/charts/whereami --version 1.2.13 --set suffix=-frontend,config.metadata=frontend,config.backend.enabled=true > helm-template.yaml
rm kustomization.yaml
kustomize create --resources helm-template.yaml
kustomize build . > helm-output.yaml
# Verify that there is no diff between the 2 outputs:
diff kustomize-output.yaml helm-output.yaml
```

For `k8s-grpc`:
```
cd ~/kubernetes-engine-samples/whereami/k8s-grpc
#Generate Kustomize overlay's output:
kustomize edit set namespace default
kustomize build . > kustomize-output.yaml
#Generate Helm chart's output:
helm template whereami oci://us-docker.pkg.dev/google-samples/charts/whereami --version 1.2.13 --set nameOverride=whereami-grpc,config.metadata=grpc-frontend,config.backend.service=whereami-grpc-backend,config.grpc.enabled=true,service.port=9090,service.name=grpc,service.targetPort=9090 > helm-template.yaml
rm kustomization.yaml
kustomize create --resources helm-template.yaml
kustomize build . > helm-output.yaml
# Verify that there is no diff between the 2 outputs:
diff kustomize-output.yaml helm-output.yaml
```

For `k8s-grpc-backend-overlay-example`:
```
cd ~/kubernetes-engine-samples/whereami/k8s-grpc-backend-overlay-example
#Generate Kustomize overlay's output:
kustomize edit set namespace default
kustomize build . > kustomize-output.yaml
#Generate Helm chart's output:
helm template whereami oci://us-docker.pkg.dev/google-samples/charts/whereami --version 1.2.13 --set suffix=-backend,nameOverride=whereami-grpc,config.metadata=grpc-backend,config.backend.service=whereami-grpc-backend,config.grpc.enabled=true,service.port=9090,service.name=grpc,service.targetPort=9090,service.type=ClusterIP > helm-template.yaml
rm kustomization.yaml
kustomize create --resources helm-template.yaml
kustomize build . > helm-output.yaml
# Verify that there is no diff between the 2 outputs:
diff kustomize-output.yaml helm-output.yaml
```

For `k8s-grpc-frontend-overlay-example`:
```
cd ~/kubernetes-engine-samples/whereami/k8s-grpc-frontend-overlay-example
#Generate Kustomize overlay's output:
kustomize edit set namespace default
kustomize build . > kustomize-output.yaml
#Generate Helm chart's output:
helm template whereami oci://us-docker.pkg.dev/google-samples/charts/whereami --version 1.2.13 --set suffix=-frontend,nameOverride=whereami-grpc,config.metadata=grpc-frontend,config.backend.enabled=true,config.backend.service=whereami-grpc-backend,config.grpc.enabled=true,service.port=9090,service.name=grpc,service.targetPort=9090 > helm-template.yaml
rm kustomization.yaml
kustomize create --resources helm-template.yaml
kustomize build . > helm-output.yaml
# Verify that there is no diff between the 2 outputs:
diff kustomize-output.yaml helm-output.yaml
```

</details>

Note: I think we should simplify and do a better job with this Helm chart regarding the `grpc` setup, there is too many parameters to set. I may land to have more intelligence in this Helm chart with a smarter `grpc.enabled` abstracting the set of all the values... food for thoughts... maybe in a second iteration/PR...

### CODE REVIEW

**Comment by theemadnes** [comment]
unless you want me to review while you're working through it

**Comment by mathieu-benoit** [comment]
@theemadnes, I will give you a heads up when it's ready for your review, I have still couple of tests/work to do, almost there :)

**Comment by theemadnes** [comment]
super cool. thanks for doing this. i'm still on chat and itching to do some work before i get back to the office on the 12th.

**Comment by mathieu-benoit** [comment]
Ready for your review @theemadnes, thanks!

**Comment by theemadnes** [comment]
need to spend some more time with this (and this won't effect non-Googlers) but there are some guides ([go/mci-asm-setup](http://go/mci-asm-setup) that will break because they use Kustomize overlays that reference the `configmap` suffixes

**Comment by theemadnes** [comment]
the problem is that the guide was taken over by PSO (i think) and it's really difficult to update directly - there's a buganizer link at the top of the doc to submit edits. let's chat about best way to address, cool?

**Comment by theemadnes** [comment]
i know it's sloppy to have the `configmap` and `ksa` suffixes - do we have to remove them for now? anyways, don't have a strong opinion either way, but don't want to break stuff for folks that use the internal guides so yeah let's chat

**Comment by mathieu-benoit** [comment]
Hi @theemadnes, yeah really good point about the breaking changes involved with the name changes: `whereami-configmap`, `whereami-ksa`, `whereami-grpc-conigmap` and `whereami-grpc-ksa`. FYI I did a `Code Search` internally, and they are not used in our public docs, that's a good news.

But yeah, the guide you mention is. Are they used elsewhere? That's difficult to answer and yes that could break them out there. I can contact the authors of the guide you shared to update it accordingly, but for the others that will be very difficult.

2 options:
1. We live with that, knowing/guessing that maybe the impact is minimal?
2. We don't want to guess/ we don't want any breaking change, so I find another way to keep existing and adapt the Helm chart.

I'm totally fine with 2., Helm chart are very flexible. Let me know what you want me to do :)

**Comment by theemadnes** [comment]
> Hi @theemadnes, yeah really good point about the breaking changes involved with the name changes: `whereami-configmap`, `whereami-ksa`, `whereami-grpc-configmap` and `whereami-grpc-ksa`. Thanks for raising this!
> 
> FYI I did a `Code Search` internally, and they are not used in our public docs, that's a good news.
> 
> But yeah, the guide you mention is. Are they used elsewhere? That's difficult to answer and yes that could break them out there. I can contact the authors of the guide you shared to update it accordingly, but for the others that will be very difficult.
> 
> 2 options:
> 
> 1. We live with that, knowing/guessing that maybe the impact is minimal?
> 2. We don't want to guess/ we don't want any breaking change, so I find another way to keep existing and adapt the Helm chart.
> 
> I'm totally fine with 2., Helm charts code is very flexible (`if...then...else`, etc.). Let me know what you want me to do :)

i'm the author of the doc, but it's gone through all sorts of formatting that i dont control any more. but i think i like your first option. we use your changes and i make the required updates to the internal guide(s).

**Comment by theemadnes** [comment]
i'll make the updates monday and merge the changes then if that's cool - i saw some folks in the doc so i want to make sure they happen at roughly the same time.

**Review by theemadnes — APPROVED** [review]
LGTM approved

**Pull request merged**
