### PR TITLE
Add samples for LLM multi-host GPUs tutorials

### PR DESCRIPTION
**Pull request by Edwinhr716**
## Description

* This pull-request adds samples for cl/663150039.

## Tasks

* [X] The [contributing guide](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/.github/CONTRIBUTING.md) has been read and followed.
* [X] The samples added / modified have been fully tested.
* [X] Workflow files have been added / modified, if applicable.
* [X] Region tags have been properly added, if new samples.
* [X] All dependencies are set to up-to-date versions, as applicable.

### CODE REVIEW

**Review by NimJay — APPROVED** [review]
Thanks for this contribution, @Edwinhr716!
Looks good to me. :)

**Question:** Which cloud.google.com tutorial is this for?

**Issue:** Judging from [the requirements outlined here](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/.github/CONTRIBUTING.md#samples-requirements), it sounds like you'll need a README.md for this folder.

**Comment by Edwinhr716** [comment]
This is for a guide that is in the process of being released, it is a Multi-Host GPU tutorial using vllm. I'm preparing the files for the release.

As for the README.md, I can add it but I'm not sure if it is a hard requirement. I submitted this PR https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/1396 a couple of weeks ago without having to add one.

**Comment by NimJay** [comment]
Thanks for the quick response, @Edwinhr716! :)

Sounds good. Let's omit the README.md file — it's tedious work.
As a follow-up, I've created https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/issues/1421 (ideally, README.md files would be automatically generated).

Ping me (@NimJay) when this is ready for merging.

**Comment by Edwinhr716** [comment]
@NimJay it is ready for merging!

**Pull request merged**
