### PR TITLE
GKE Stateful Postgres code

### PR DESCRIPTION
**Pull request by aburhan**
code for reference guides on deploying GKE Stateful Postgres

### CODE REVIEW

**Comment by bourgeoisor** [comment]
@aburhan what is your maintainability plan for this directory? That's a lot of files and beyond what our team could consider adding to our load. Who would own this directory's content and be on the hook for any issues arising in it?

**Comment by bourgeoisor** [comment]
Yes, see example here: https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/CODEOWNERS#L9

**Comment by bourgeoisor** [comment]
@aburhan could you add:
- A top-level README in the `gke-stateful-postgres` directory that explains what the code samples are for, where they are used (I understand this is a chicken-and-egg problem since the tutorials may not be published yet), etc. See an example [here](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/tree/main/hello-app).
- A workflow in the `.github/workflows/` directory that makes sure that any changes to this directory are tested properly. This can include building Docker containers or doing a dry-run of the Terraform script, for example. (If you don't have access to push changes to that directory, I'm happy to create a new workflow for this directory for you -- just let me know what it should look like)

**Comment by aburhan** [comment]
> 

updated

**Review by bourgeoisor — APPROVED** [review]
LGTM

**Pull request merged**
