### PR TITLE
Use AR — not GCR — in README.md files

### PR DESCRIPTION
**Pull request by NimJay**
## Background
* AR = Artifact Registry
* GCR = Google Container Registry
* In https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/issues/209, we replaced all instances of GCR (inside Kubernetes manifests) with AR.

## Change Summary
In this pull-request:
* we're replacing all instance of GCR samples with AR samples inside `README.md` files.

## How to Review
1. Make sure the URLs are correctly replaced.
2. `Ctrl/Command` + `Shift` + `F` and search `gcr.io/google-samples` in Visual Studio (ignore `cloudbuild.yaml` files). Make sure I haven't missed anything.

### CODE REVIEW

**Comment by bourgeoisor** [comment]
Do we have to move or copy images from GCR to AR, or are those references automatically created?

**Comment by askmeegs** [comment]
> Do we have to move or copy images from GCR to AR, or are those references automatically created?

Nim has already set up our CI for this repo to build + push to both places. :) 
example - https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/main/hello-app-redis/cloudbuild.yaml

**Comment by NimJay** [comment]
> Do we have to move or copy images from GCR to AR, or are those references automatically created?

@bourgeoisor, sorry, I should've elaborated a bit more in the PR description. :)
No copying/moving of images is necessary.
This pull-request involves the following images:
* `hello-app-cdn:1.0`
* `hello-app-redis:1.0`
* `whereami:v1.2.6`

which were first pushed to Artifact Registry via #185.

If you would like to double check that the AR (replacement) images and GCR (replaced) images are equivalent, you can do something similar to:

1. Pull the 2 images you want to compare:
```
docker image pull gcr.io/google-samples/hello-app-redis:1.0
docker image pull us-docker.pkg.dev/google-samples/containers/gke/hello-app-redis:1.0
```
2.  Inspecting both images:
```
docker image inspect gcr.io/google-samples/hello-app-redis:1.0
docker image inspect us-docker.pkg.dev/google-samples/containers/gke/hello-app-redis:1.0
```
3. See that the [RootFS values match](https://stackoverflow.com/questions/46321878/how-to-verify-if-the-content-of-two-docker-images-is-exactly-the-same/46322160#46322160).

Thank you!
Let me know if you I should clarify anything else.

**Review by bourgeoisor — APPROVED** [review]
This looks good to me!

**Pull request merged**
