### PR TITLE
feat: samples for upcoming Zalando Postgres DR tutorial

### PR DESCRIPTION
**Pull request by ganochenkodg**
Terraform and yaml code for the "Zalando: Disaster recovery" guide.

### CODE REVIEW

**Review by bourgeoisor — COMMENTED** [review]
- Make sure to add license headers where necessary (see the failed check, if applicable)
- Make sure to add region tags surrounding code that will be embed in a tutorial, e.g. (`# [START gke_databases_postgres_zalando_name_of_file]`)
- Are the changes to the `postgres` directory intentional? Is that another tutorial?

**Comment by ganochenkodg** [comment]
@bourgeoisor Olivier, about header checks - can someone update databases-ci.yaml or should I add the header in one of my PRs?

**Comment by ganochenkodg** [comment]
>Are the changes to the postgres directory intentional? Is that another tutorial?
@bourgeoisor Yep, it's a code for advanced Zalando guide with replication and backups. We decided to split basic and advanced PRs, so this one probably should be merged first https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/pull/972

**Comment by bourgeoisor** [comment]
@ganochenkodg would you mind rebasing this PR or merging latest into it? It should fix the database ci failing. Thanks!

**Review by bourgeoisor — APPROVED** [review]

**Comment by bourgeoisor** [comment]
LGTM to me, @ganochenkodg lemme know when it's ready to be merged in

**Comment by bourgeoisor** [comment]
Since the initial Zalando PR was merged, there are minor merge conflicts here that needs to be resolved.

**Comment by ganochenkodg** [comment]
@bourgeoisor fixed

**Pull request merged**
