### PR TITLE
feat: samples for upcoming Zalando Postgres operator tutorial

### PR DESCRIPTION
**Pull request by ganochenkodg**
Terraform and yaml code for the Zalando guide.

### CODE REVIEW

**Review by bourgeoisor — COMMENTED** [review]
- Make sure to add license headers where necessary (see the failed check, if applicable)
- Make sure to add region tags surrounding code that will be embed in a tutorial, e.g. (`# [START gke_databases_postgres_zalando_name_of_file]`)

**Comment by ganochenkodg** [comment]
@bourgeoisor Olivier, about header checks - can someone update databases-ci.yaml or should I add the header in one of my PRs?

**Comment by ganochenkodg** [comment]
okay, anyway, i will add headers and we can resolve conflicts later

**Comment by bourgeoisor** [comment]
@ganochenkodg would you mind rebasing this PR or merging latest into it? It should fix the database ci failing. Thanks!

**Review by bourgeoisor — APPROVED** [review]

**Comment by bourgeoisor** [comment]
LGTM to me, @ganochenkodg lemme know when it's ready to be merged in

**Pull request merged**
